Vagrant.configure(2) do |config|
  config.vm.box = "anthshor/OracleLinux66"
  config.vm.hostname = "logitech.sprite.zero"
  #to cache yum
  config.vm.synced_folder "~/Dropbox/Hashicorp/Vagrant/yum", "/var/cache/yum", create: true
  config.vm.synced_folder "~/Dropbox/Hashicorp/Vagrant/software", "/u01/software", create: true
  config.vm.network "private_network", ip: "192.168.33.11" 
  config.vm.provider :virtualbox do |vb|
    unless File.exists?('asmdisk1.vdi')
      vb.customize ['createhd', '--filename', 'asmdisk1', '--size', '5128']
    end  
    vb.customize ['modifyvm', :id, '--memory', '4096']
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', '1', '--device', '0', '--type', 'hdd', '--medium', 'asmdisk1.vdi']
    vb.name="whistlera"
  end
  #config.vm.provision "shell",  path: "provision.sh"
end
